### ISSUE TITLE
Transcript-level TPM expression values do not sum  up to Gene-level TPMs

### ISSUE THREAD

**Issue by naumenko-sa** [broadinstitute/gtex-viz#207]
Hello, gtexportal developers!

Thanks for such a useful portal!

I've noticed that if you sum up transcript-level expression TPM values of a gene, the sum would not be equal (even approximately) to the gene-level expression TPM value.

For example, https://gtexportal.org/home/gene/SELL
is expressed in Whole Blood at 1349 TPM (median),
and it has 6 isoforms expressed at 490 + 4.2 + 1.04 + 3.83 + 0.380 + 1.51 = 500.96 TPM

Why there is a difference between 1349 TPM and 500.96 TPM?
Is it because isoform-level transcript values are means and gene-level are medians,
or because of different quantification methods? (RNA-seqQC for genes and RSEM for transcripts?)

Thanks!
Sergey

**Comment by jnedzel** [comment]
Hi Sergey, 

Please use the contact page for this question: https://gtexportal.org/home/contact

The contact page goes to the entire GTEx Portal team, including our computational biologists and PI.  Our computational biologists probably won't see this question as this repository is only used by our software developers.  

It is fine to post issues in here that relate specifically to the gtex-viz package, but general GTEx questions will be answered faster when posted via the contact page.

Thanks,

Jared Nedzel

**Comment by vinkwok** [comment]
> Hello, gtexportal developers!
> 
> Thanks for such a useful portal!
> 
> I've noticed that if you sum up transcript-level expression TPM values of a gene, the sum would not be equal (even approximately) to the gene-level expression TPM value.
> 
> For example, https://gtexportal.org/home/gene/SELL
> is expressed in Whole Blood at 1349 TPM (median),
> and it has 6 isoforms expressed at 490 + 4.2 + 1.04 + 3.83 + 0.380 + 1.51 = 500.96 TPM
> 
> Why there is a difference between 1349 TPM and 500.96 TPM?
> Is it because isoform-level transcript values are means and gene-level are medians,
> or because of different quantification methods? (RNA-seqQC for genes and RSEM for transcripts?)
> 
> Thanks!
> Sergey

hello Sergey, I also have such question, did you find the answer to your question?

Thanks,
Wenbin

**Comment by naumenko-sa** [comment]
Hi Wenbin!

I used the form above and they responded by email! 
Unfortunately, I don't have access to that mailbox anymore.
I vaguely remember they were using historically two different tools to calculate TPM/counts and they were going to fix that. Better ask them again!

Sergey
