### ISSUE TITLE
Isoform expression widget shows ENSEMBL_GENE_ID instead of ENSEMBL_ISOFORM_ID in the pop-up window

### ISSUE THREAD

**Issue by naumenko-sa** [broadinstitute/gtex-viz#210]
Hello, gtex portal developers!

Thanks for the great portal!

When I'am viewing isoform expression in a particular tissue, for example
https://gtexportal.org/home/gene/SMN2, hover mouse over "Spleen" vs the first isoform in the list (ENST00000380743.4), the pop-up window shows tissue, isoform, and TPM, and instead of isoform ID it shows GENE_ID. 

Could you please fix it to show isoform ID?

Sergey

**Comment by kataviz** [comment]
Thank you for reporting this issue. It should be fixed.
